### PR TITLE
Feature:  Command Logger

### PR DESCRIPTION
**Pull request by bnert**
This series of commits implements the ability to log commands and recall them by using the up/down arrows keys while in the console.

In addition, I also segmented the EventLoop logic to its own class in order to keep the main loop concise.

### CODE REVIEW

**Review by FarrarE — COMMENTED** [review]
I believe that merging this will break the timer, causing it to not reset on user input.

**Comment by bnert** [comment]
It will, I am currently working on porting the functionality in order to keep the timer from breaking

**Comment by bnert** [comment]
@FarrarE Would you be able to take a look again? I have fixed the merge conflicts and tested.

**Review by FarrarE — APPROVED** [review]
That looks like it will solve all our issues, good job!

**Pull request merged**
